### ISSUE TITLE
Some questions about CT imaging parameters

### ISSUE THREAD

**Issue by lijiajun2077** [HPImaging/sv-mbirct#12]
This code runs fast, I want to do some tests. But I don’t have sinogram data, I only have a 4096 * 4096 CT image. I use this code to create the system matrix, and then get the projection from the system matrix and the image. Finally, the projection is used as sinogram data to reconstruct the original image. 
I don’t know much about CT imaging. I have some questions about CT imaging parameters. For this 4096 * 4096 CT image, how to set the parameters DeltaChannel, NChannels and Deltaxy?  I want to do CT imaging with 480 view angles, and I set the parameter DeltaChannel to 1,  NChannels to 1500 and Deltaxy to 0.25. Is this setting the parameters correctly？

**Comment by sjkisner** [comment]
For a simulation there's not a single correct answer. Those settings should work OK. Note you have to set all these parameters for the sinogram and image geometry *before* creating the system matrix.
