### ISSUE TITLE
Adding parallel for loops for A matrix compute 

### ISSUE THREAD

**Issue by svvenkatakrishnan** [HPImaging/sv-mbirct#13]
Given its takes time to compute the A-matrix especially for large volumes, would it be possible to make the core for loop a parallel for ?

**Comment by sjkisner** [comment]
A_comp() and A_piecewise() were parallelized with omp.  These are very memory intensive with a lot of malloc calls.  A_comp() works good on a lot of threads. A_piecewise() is set to a maximum of 4 threads..beyond that the run time can increase.
